### ISSUE TITLE
Errors with loading scenes

### ISSUE THREAD

**Issue by Flintwyrm** [trdischat/lessfog#14]
When I load my world the scene is stuck like this and I cant move it. Also none of the buttons on the side work. 
![Screenshot_2048](https://user-images.githubusercontent.com/60701064/122053357-acb0b000-cdb4-11eb-981a-4007409c446b.png)
These are the errors I get upon loading the world.
![Screenshot_2046](https://user-images.githubusercontent.com/60701064/122053430-bb976280-cdb4-11eb-9354-92233efec7bd.png)
![Screenshot_2047](https://user-images.githubusercontent.com/60701064/122053432-bb976280-cdb4-11eb-84a9-b92ac2b3d3ee.png)
![Screenshot_2045](https://user-images.githubusercontent.com/60701064/122053433-bb976280-cdb4-11eb-9f69-dc0bce2deb79.png)

Uninstalling Less Fog fixes the issue.

**Comment by burndaflame** [comment]
Got the same error. Looking into the code and earlier error-messages showed, that somehow ´lib - ColorSettings´ was disabled.
Enabling it fixed everything.

**Comment by Majea** [comment]
Same for me. None of my scenes were showing. There was a stack trace on the WelcomScreen file in the console. I disabled the module and the dependent ones. Then I re-enabled them and only at that moment it suggested to enable the ColorSettings module, which fixed the issue. 
While the problem is easy to fix, it's actually not that easy to find out what to do. Someone with no programing skill may have a hard time finding out.

**Comment by trdischat** [comment]
When I released version 0.8.2, I screwed up and failed to include lib-ColorSettings as a dependency in the module.json file.  I fixed it and uploaded version 0.8.3 minutes later.  It looks like some folks managed to download version 0.8.2 and not 0.8.3 and got stung.  As far as I can tell, this problem should not recur as long as you have the current version of the module.  Let me know if this does not fix it.  Thanks.
