### ISSUE TITLE
Levels Support

### ISSUE THREAD

**Issue by mouse0270** [trdischat/lessfog#21]
It appears that you at one point had this module working with levels, however with the latest version of both running on the latest version of foundry, this appears to no longer work.

**Comment by mouse0270** [comment]
Just looked in the source and realized that this is disabled if levels is enabled

**Comment by mouse0270** [comment]
So LessFog and Levels are way to important for me to pick between. So I wrote some logic to provide some basic support to levels in LessFog. Its not perfect but its better then nothing.
```javascript
Hooks.on("sightRefresh", layer => {
    let levelsRange = (_levels.UI.definedLevels.length > 0 && _levels.UI.range.length > 0) ?? false;
    for (let t of canvas.tokens.placeables) {
        if (levelsRange) {
            if (_levels.UI.range[0] <= t.data.elevation && t.data.elevation <= _levels.UI.range[1]) {
                t.visible = (game.user.isGM || game.settings.get("lessfog", "affect_all")) || t.isVisible;
            }else{
                t.visible = false
            }
        }
    }
});
```
Use it or don't, but thought I would share it at the very least.

**Comment by trdischat** [comment]
I am not fully understanding the issue here. The only thing that is disabled in Less Fog when Levels is installed and enabled is the setting in Less Fog to make all tokens visible to the GM at all times. I disabled that one setting because Levels needs to have very granular control over the visibility of tokens in order for it to work. I made this change at the request of the author of the Levels module and am not thrilled about the idea of tinkering with the Levels system in my module. Other than this one setting, everything else in Less Fog should still work. What exactly is it that you want to accomplish that is not currently working?

**Comment by AndreCaseyScott** [comment]
> Other than this one setting, everything else in Less Fog should still work. What exactly is it that you want to accomplish that is not currently working?

I think that is the real issue. It doesn't work with Levels. Tried to "find the culprit" and it seems to be a direct conflict with LessFog and Levels (with it's dependencies).
![Screenshot 2022-07-06 09 50 33](https://user-images.githubusercontent.com/3774345/177603106-c70e0df3-c5b0-41ee-80c6-47712fda0520.png)

**Comment by AndreCaseyScott** [comment]
> I think that is the real issue. It doesn't work with Levels. Tried to "find the culprit" and it seems to be a direct conflict with LessFog and Levels (with it's dependencies). 

Immediately after posting this I decided to continue fiddling with settings and found the magic button. "Fog Exploration" needs to be checked for this to work. In hindsight, seems obvious since the module is called "LessFog", but I've had so many issues with the fog exploration that I normally leave it unchecked on scenes, relying on SimpleFog or similar. 
![Screenshot 2022-07-06 09 58 01](https://user-images.githubusercontent.com/3774345/177604468-707b0191-0757-4f58-b115-8ea37fe7871d.png)

Hope this helps someone else with this issue.
