### ISSUE TITLE
Unexplored areas are not fully opaque for players, and can therefore still be seen by players

### ISSUE THREAD

**Issue by BuggStream** [trdischat/lessfog#6]
With foundry 0.7.5 and lessfog 0.6.7, unexplored areas on the map are not fully opaque for players. So players can quite easily view the entire layout of the map. This makes the lessfog module currently unusable for me sadly. I am not sure if this is intended behavior, if it is it'd be useful to add an option to disable this.

Here is how the exact same scene looks **without** lessfog:

![image](https://user-images.githubusercontent.com/51194915/97106033-91772000-16bf-11eb-8f22-1e4ad23b3b19.png)

**With** lessfog:

![image](https://user-images.githubusercontent.com/51194915/97106047-a8b60d80-16bf-11eb-9924-c214406d70f0.png)

Settings of the module:

![image](https://user-images.githubusercontent.com/51194915/97106088-da2ed900-16bf-11eb-8524-50266e875c62.png)

**Comment by JJBocanegra** [comment]
Yes, I just realized this and just deactivate the module because all my players can see all the map.

With the module:
![image](https://user-images.githubusercontent.com/5797636/97206841-915b4b00-17b9-11eb-8e98-3235b44f4661.png)

Without the module:
![image](https://user-images.githubusercontent.com/5797636/97206900-a0da9400-17b9-11eb-8758-7f4b6a529a81.png)

**Comment by trdischat** [comment]
Please try version 0.6.8, which I just uploaded.  Unfortunately, with FVTT 0.7.x, it is no longer possible to reveal the unexplored areas to the GM only.  The new module version removes this option and leaves the unexplored color as fully black for everyone.
